name: gai-gs
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults

dependencies:
  - python=3.12.7
  - pip
  - numpy=1.26.1
  - scipy=1.13.1
  - matplotlib=3.9.2
  - pillow=11.0.0
  - tqdm=4.66.5
  - pandas=2.2.3
  - pyyaml=6.0.2
  - tensorboard
  - imageio=2.33.1
  
  # PyTorch with CUDA
  - pytorch=2.3.1
  - torchvision=0.18.1
  - pytorch-cuda=12.1
  
  # pip packages
  - pip:
    - einops==0.8.1
    - joblib==1.4.2
    - plyfile
    - opt-einsum
    - clifford
    
# After creating the environment, install the submodules:
# 
# conda activate gai-gs
# 
# # Install diff-gaussian-rasterization
# cd submodules/diff-gaussian-rasterization
# pip install .
# cd ../..
# 
# # Install simple-knn
# cd submodules/simple-knn
# pip install .
# cd ../..
# 
# # Install fused-ssim
# cd submodules/fused-ssim
# pip install .
# cd ../..
